### ISSUE TITLE
On 4.11.3 and 4.12.1 gzdoom color translation broken

### ISSUE THREAD

**Issue by RonDallas** [Sumwunn/DoomRPG#101]
4.11.3 and 4.12.1 gzdoom broke color translation in the DRPG.
https://media.discordapp.net/attachments/393878865409343488/1252694670920777819/image.png?ex=66732653&is=6671d4d3&hm=214f924854dd926e5cb86ee1d3111fe0cde990cd0ecf6eb8c55202efd7b565d1&=&format=webp&quality=lossless&width=1101&height=592
![image](https://github.com/Sumwunn/DoomRPG/assets/32035822/9b107af1-170c-4a07-81c6-a13a571827dc)

**Comment by Wickez** [comment]
Alright. Now I understand why this fork's maintainer doesn't reply to almost any issues.

**Comment by RonDallas** [comment]
> Alright. Now I understand why this fork's maintainer doesn't reply to almost any issues.

tell me

**Comment by Sumwunn** [comment]
I stopped working on this a couple weeks ago because I got fed up with wasting evenings trying to figure out the latest issues (email notifications are off because they were stressing me out).

It doesn't help that I'm only somewhat familiar with Base DRLA + Monsters (I seldom play DRPG) so the newer stuff (like DRLAX or Rebalance features) is unknown to me. This fork was intended to just sync Rebalance changes but with my backend fixes, for the above reason.

That being said, I'll probably give DRPG another go sometime in July. For now, I'm trying my hand at a simplistic addon for HXRTC/F that ties monsters/items/weapons to player level (+difficulty tweaks) written in ZScript (my first mod!).

**Comment by Sumwunn** [comment]
Decided that I want any issues here related to Rebalance posted to Rebalance's page so the actual devs/everyone can see them, which allows proper issue tracking, along with preventing a Dev disconnect between this and Rebalance.

I will still attempt to work on Rebalance itself, but not on this fork (it will go dark to prevent newcomers from breaking their game).

Remember: this a sync fork, meant for keeping up to date with Rebalance's changes while I rework major parts of DRPG's core. Also, please adhere to the readme where it says only compatible mods work. Too many people load a ton of things afterwards and then you have mods overwriting each others functionality (see Champions and Cosmo Ambience.

**Comment by Sumwunn** [comment]
Changed a few things; two new branches:

Rebalance-Master
- Contains Rebalance with changes deemed stable/safe for playthroughs.

Rebalance-Dev
- Contains Rebalance with changes deemed unstable/unsafe for Master until otherwise.

This is a bit clearer and eases testing for Rebalance specific issues easier as I can separate dev issues from master issues.

**Comment by FoxMcloud5655** [comment]
Thanks for making them separate branches, as it'll take quite some time to update my own version to be compatible with the rebalance.

**Comment by Sumwunn** [comment]
What I posted in Discord:

For those wondering why Rebalance-Master went poof: decided that trying to migrate fixes from Dev to Master was a headache (many changes). Honestly, working on Rebalance has been a bit of a mess for me since I couldn't tell if the recent issues were part of original Rebalance or my changes (I wasn't part of Rebalance development). Decided to return to the single rebalance-dev branch and honestly just fix it up the best I can.

Also, since map code rework, similar functionality with map packs will return, allowing the use of either WadSmoosh + Compendium or Lexicon.

Lastly, the main changes in the dev fork are meant to mitigate hard crashes, so if the official Rebalance is working fine for you, not too much reason to switch (unless you're feeling experimental).

**Comment by Sumwunn** [comment]
@RonDallas 

Do you have an older GPU by any chance? I can't reproduce this issue on the versions listed, so I'm wondering if the renderer in those versions is causing issues for you.

**Comment by RonDallas** [comment]
@Sumwunn 
Vega 11 from Ryzen pro 3400ge (integrated one). 4.12.2 is the same thing:
![image](https://github.com/user-attachments/assets/59523a9a-4b46-47bd-abd2-d253843b7893)

**Comment by Sumwunn** [comment]
The only clue is Vega is stuck on a older driver branch (I have RDNA2), but still doesn't explain why (since Vega still gets updates).

Grrr, fuck this mod some days, seriously...

**Comment by RonDallas** [comment]
Got P106-100 (mining 1060). GZD above 4.10 have same thing. Also, pandemonia bosses have thing that clean them from visual effect of shadow aura (but on 4.10 they still have it).
