### ISSUE TITLE
Money lagging

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#22]
When in a really big sector if you accumulate tons of money sprites without collecting them (because of too many demons in your way for example) It start lagging fairly bad, 

Comp spec:

Motherboard: i7 3770k 3.50ghz
Video card: Geforce gtx 960
Ram : 16go 1333 mhz

Suggestion: maybe remove dynamic light bloom on money drops altogether? Instead make em glowing like a lost soul , would remove a fair bit of useless light calculation in the level tbh...

(Btw it stopped lagging immediately when I pressed the magnetize skill so its most likely what cause said lag.)

**Comment by Sumwunn** [comment]
Yeah this just seems to be GZDoom choking on everything that's happening. Doesn't matter how good your PC is.

I'm not aware of anyway to turn off individual lights but you could just comment out the credit lights in GLDEFS.txt or use the new virtual credits option which transfers the credits directly to you instead of dropping them.

**Comment by Forevener** [comment]
I've made an option called 'Virtual Credit Drops' for that occasion, it's in the performance options. It doesn't make all drops virtual, though - like credits from the "Rainbow" event or megabosses.
