### ISSUE TITLE
Adaptive difficulty setting reverts to Standard.

### ISSUE THREAD

**Issue by devilemporium** [Sumwunn/DoomRPG#44]
As the title says. When you choose Adaptive difficulty from starting the game, two errors come up saying that non-existing actors are being called to replace the Blue and Green armor.  <- (Might not be relevant) When you try to change the difficulty through the Outpost, the game shows that it is on Standard instead of Adaptive, which is proven by reinforcements not spawning naturally. The same occurs when you change to Adaptive, play a map, go back to Outpost, and the difficulty has reverted to Standard.

**Comment by Sumwunn** [comment]
Yeah after looking into it some more I'm going to have to rework how DRPG's actors get replaced, shouldn't take too long. For the mean time I'd avoid adaptive.

Since the only way to change a skill level via ACS is numbers; standard (same as UV, which adaptive starts at) is going to get replaced with adaptive for selection.

**Comment by Sumwunn** [comment]
Ok so after finding out that the DRLA adaptive armour replacers are not actually completed yet I simply commented the replacers out. I've also replaced Standard with Adaptive, so no more visual oddities. The adaptive monster replacers should work.

Reinforcements was a side effect of Adaptive having GameSkill() = 7 (supposed to be 3). Since reinforcements spawn on Hell and above by default. 
If you liked having to fight reinforcements you can go into the Game Difficulty settings and enable them to always spawn regardless of difficulty.
