### ISSUE TITLE
Plans to support the updated Doom RLA, RLA Monsters and LegenDoom mods?

### ISSUE THREAD

**Issue by BoneofMalkav** [Sumwunn/DoomRPG#59]
Any plans to update to support the updated versions of Doom RLA and LegenDoom?

**Comment by Sumwunn** [comment]
Hey there, sorry about the long delay.

I started university (majoring in IT) about 3 weeks ago and have been working on assignments more or less everyday since. I'm trying to get Bs in all my classes. I think the only break I'm going to get is when my semester concludes which is in December.

I know, that's a horribly long wait. Apologies. :((((((((((((
However, do not fear, I don't plan to forget about DRPG. I will continue working on it when I get chunks of free time, even if thats years from now.

I am open to any pull requests.
I need to post this on the forum sometime.

**Comment by BoneofMalkav** [comment]
No worries dude take your time.

**Comment by Sumwunn** [comment]
Hey I've added what changes I've found to DRPG.

The update currently resides in experimental as I still need to go over the files.

https://github.com/Sumwunn/DoomRPG/tree/experimental

**Comment by Sumwunn** [comment]
Update: Changes are in master now, couldn't find anything else to add.
