### ISSUE TITLE
Game freezing after loading a saved game

### ISSUE THREAD

**Issue by Daniel-Leontiev** [Sumwunn/DoomRPG#64]
After playing for several hours, saving a game. Loading the game the next day, and the game freezes after a minute of play time, tested it with several version of GZDoom x64/x32, with different graphics options, so it's not a video card or driver issue.

**Comment by Daniel-Leontiev** [comment]
I think this might be related to Shadow enemy type.

**Comment by FoxMcloud5655** [comment]
I've had this issue before. A quick fix is to save your character, start a new game, then load your character again.

**Comment by themaster567** [comment]
Having this issue as well. Is there anything that can be done besides this?

**Comment by Sumwunn** [comment]
This will probably not be fixed anytime soon, if at all. I read somewhere
on ZDoom forum that the function HUDMESSAGE which is something that DRPG
uses a ton, is a nightmare itself and can cause GZDoom to freeze if abused
which DRPG certainly does.

I do not believe it is possible to send strings to ZScript in any way so
unfortunately, this cannot be resolved as of right now.

That's considering HudMessage is even the issue here this time.

:(

**Comment by WNC12k** [comment]
Which version of gzdoom are you using? And what's the loading order?

**Comment by themaster567** [comment]
> Which version of gzdoom are you using? And what's the loading order?

I was using GZDoom 3.8 Vintage and [this load order](https://i.imgur.com/ktvnFLR.png), but now, per suggestion, I'm using 4.1.3 and [this load order.](https://i.imgur.com/fk8cesM.png)

**Comment by Sumwunn** [comment]
Not sure if it will help with the freezing, but DoomRPG.pk3 should placed after DRLA and just before any DRPG patches.

**Comment by Daniel-Leontiev** [comment]
I've got it working well now, here's my load order:
`gzdoom.exe +sv_cheats 1 +logfile "Doom RPG.log" -file "DRLA\DRLA_1.1.2.pk3" "DRLA\DRLM_7.2.pk3" DoomRPG\DoomRPG DoomRPG\DoomRPG-Brightmaps DoomRPG\DoomRPG-Extras DoomRPG\DoomRPG-RLArsenal DoomRPG\DoomRPG-RLMonsters`

**Comment by Sumwunn** [comment]
Remove Extras from your load order as it will cause conflicts with DRLA and you're sorted. :)

**Comment by Daniel-Leontiev** [comment]
Great thank you!

I was wondering about the `DoomRPG-WadSmoosh`

I have the latest version of `doom_complete.pk3` that I've compiled using `WadSmoosh` that includes `Sigil`.

Sigil is defined as `E5M1` - `E5M9`, how would I integrate that into `DoomRPG-WadSmoosh`
I see there are 2 files in question `CVARINFO.txt` and `MAPINFO.txt`

**Comment by Sumwunn** [comment]
Are you still having this issue? I posted a fix for the freeze on my thread so you can apply it on the spot if you're having issues still.

https://forum.zdoom.org/viewtopic.php?style=12&f=19&t=63766&start=105#p1124474

**Comment by Sumwunn** [comment]
Hey, since no one else is having issues with freezes so far I'm going to assume this particular issue is fixed.

If you encounter any more freezes please post another thread along with your save game, load order, and version stuffs.

I'll pin an issue here pointing people to the freeze fix until the next DRLA update comes out.

Cheers.

**Comment by Daniel-Leontiev** [comment]
Hey, sorry for late response, I've tested the game for several hours, and it does not freeze anymore when Shadow enemy is present!

I've applied the fix no problem!

Thank you for the fix!
