### ISSUE TITLE
When a monster with the level up aura activate (white/silver) it fully heal + Beretta bug + Watcher's missing attack

### ISSUE THREAD

**Issue by Demiosis** [Sumwunn/DoomRPG#71]
Title's pretty self explanatory, and since there's no options in the White aura to turn that off im preeeety sure thats a bug. (Its when the white aura mass level up activate) (did some more tests and myhea no wonder why some boss are just unkillable , 2 auras that fully heal it... kinda unfair.. XD)

Also on another note , seem's the Grammation Cleric Beretta do not get his 5 secs damage buff with Firestorm modpack (Seemed to work with DRLA only.)

Finally, I tested the watcher on drla only and seem its missing its *look at it* attack and since its the main replacement for imps ironically enough, they are currently : Melee only , mediocre damage if they by miracle get to hit you, pretty slow compared to the other monsters AND made of 2 folds of cardboard... ^^''' If you can't fix it I suggest simply removing it , regular imp variant are more dangerous than this joker..

Setup: "GZDOOM.exe" -file "mymap.wad" "DoomRL_Arsenal_1.1.2.pk3" "DoomRL_Monsters_Beta_7.2.pk3" "doomrl_arsenal_hud_1.05.wad" "DoomRPG.zip" "DoomRPG-RLArsenal.zip" "DoomRPG-RLMonsters.zip" "Doomrpg-BrightMaps.zip"

+ Your tiny modification to DRLA 1.1.2 bosses actors

**Comment by Sumwunn** [comment]
I took a look at the Watcher and noticed that DRLA is checking for explict class names which presents a problem because DRPG replaces monsters with "RPG" on the end, breaking the monsters behavior, yikes! I think there's a method in decorate that allows to check for part of a string which would fix it, but that depends on where Yholl stands on in terms of compatibilty with older GZDoom, in which case my best bet would be to move DRPG monster compatibility to ZScript.

Here's a list of other monsters that may be similarly busted:
RLBruiserBrother
RLArmageddonArchvile
RLArmageddonCacodemon
RLArmageddonImp
RLArmageddonLostSoul
RLAgonyElemental
RLBruiserBrother
RLBruiserBrother2
RLCyberneticSpiderMastermind
RLArmageddonSpiderMastermind
RLCyberdemon

**Comment by Demiosis** [comment]
Good to know for Armageddons monsters, and for the level up aura problem , were you able to reproduce it? ^^'

**Comment by Demiosis** [comment]
The White and silver aura was irrelevant to the monster healing abilities, this is 100% caused by regeneration and the beretta bug will most likely be fixed with the new Drla arsenal package. So this issue is now fairly pointless to keep open so im gonna close it!
