### ISSUE TITLE
Issue with loading characters after update & NashGore question

### ISSUE THREAD

**Issue by sanscriptum** [Sumwunn/DoomRPG#93]
Hi, very cool mod, enjoying it a lot so far as I marathon through all the official Doom map packs, almost done with Doom 1.

I saw that this branch (on `rebalance-sync`) got relevant updates for submods like `corruption cards` and `legendoom lite`, and seeing that my old save probably wouldn't load, I tried to save my character on the old version (master branch from WNC12k) and migrate here.

However, I got an error saying something like "your save is corrupted lol, code error 3". Well, that wasn't nice. Nothing really worked, and my only real option was to start over. I was also intrigued by the `wadsmoosh` update, which supports Sigil 2 from the hub menu, but apparently using it now conflicts with Lexicon, whaaaat?! And indeed it does, because it breaks the hub interface menu horribly, how did that even regress?

So I went back to the master branch and updated just those two submods, but guess what, they invalidated my old save anyway, so I had to use character load again. Luckily, it worked this time, but it seemed like all my map progression was erased, which isn't great - makes sense, I guess, because I read it's just for transferring your character between map packs after you finish them?

There are also some quirks with the character loading system regarding the turret - while it keeps all the upgrades, the turret comes out completely beat up and out of bullets - a bit annoying.

I was wondering, is there like a save cleaning utility for GZDoom saves that would go through them and remove/change invalid references based on your load order? Haha, this probably sounds like wishful thinking.

Anyway, I guess I can wait for the proper update on the master branch and then start with a fresh character in the future.

---

Speaking of NashGore Next - I loaded it along with the modpack thinking it lacked gore, but apparently it already has some built in via the FancyGore option. But I noticed that it really hurts performance, which is a shame because the gibs are very nice. So here is the problem - NashGore is overridden at some point, even when I load it last. Or at least, most of its features, the blood spurts and door squishing still work.

This is relevant because NashGore is much faster and much more optimized, plus it has a better gore system imo. Think Bolognese, but without stuttering every time you rocket something. Sorry to ask, but can it be ported or nah?

---

And lastly, are there no specialty backpacks at all, so there's no way to get relevant achievements? And speaking of, how many of them can be even completed? I noticed that final episode levels don't count as cleared given that they have special on kill requirement or teleport end screen, so maybe that does something? Maybe I should've used D1 compatibility?

**Comment by Someone65** [comment]
A change from rebalance-sync is that multiple map packs at the same time indeed don't work together anymore. You have to just load one of them (along with their compatibility patch) at a time. You can see the reasoning for that in commit d72012c

Saving map progress on character saving was implemented in commit 7260593 which you have! Unfortunately, since you saved your character in a version where that wasn't implemented yet (WNC's rebalance fork), it didn't save map progress. On the bright side it'll do that from now on :)

As for recovering your save, no. It's fucked. I also looked for solutions to that but it's kinda just infeasible. Made an oopsie with my save once from updating a mod and couldn't find the file for the older version anywhere and forgot I had a save.

> Speaking of NashGore Next - I loaded it along with the modpack thinking it lacked gore, but apparently it already has some built in via the FancyGore option. But I noticed that it really hurts performance, which is a shame because the gibs are very nice. So here is the problem - NashGore is overridden at some point, even when I load it last. Or at least, most of its features, the blood spurts and door squishing still work.
> 
> This is relevant because NashGore is much faster and much more optimized, plus it has a better gore system imo. Think Bolognese, but without stuttering every time you rocket something. Sorry to ask, but can it be ported or nah?

For Nashgore, there's a mod called BLUDTYPE for Nashgore which overrides the gore of mods that have their own: [https://forum.zdoom.org/viewtopic.php?f=46&t=69485](https://forum.zdoom.org/viewtopic.php?f=46&t=69485)

Problem with that mod is it has a weird issue where it doesn't work on Windows due to line endings being Unix style, which you can fix easily if you know how to... or just retype the stuff from that into a text file with notepad yourself lol (idk if copy pasting into notepad will also copy the line endings since I use something else).

Considering you mentioned Fancy Gore, I guess you're referring to DRLA Monsters. DRLA Monsters uses an older, slightly modified version of Nashgore and it honestly lags about just as much in the short term (so if you gib a ton of enemies at once it'll still lag badly from that) but helps with the lag that accumulates over time with its more customizable options for limiting blood and gibs and I think it also stops blood that's far away enough from rendering.

> And lastly, are there no specialty backpacks at all, so there's no way to get relevant achievements? And speaking of, how many of them can be even completed? I noticed that final episode levels don't count as cleared given that they have special on kill requirement or teleport end screen, so maybe that does something? Maybe I should've used D1 compatibility?

IDK about the D1 completing achievements (actually testing it right now in a playthrough) but the backpack issue is really just a big design problem that WNC didn't wanna tackle. Backpacks in DRPG have switched roles to just being big, universal ammo packs since the capacity stat serves their original purpose. You would have to redesign all the backpacks to be properly balanced with DRPG's mechanics which is a big undertaking as you'd probably have to rework the capacity stat as a whole (and probably a bunch of other things, including the skill that gives ammo and the luck stat) in order to make it fair and balanced. I guess if you want to earn impossible achievements, you'll just have to use the same .ini file and earn them without playing DRPG.

**Comment by sanscriptum** [comment]
Excellent, thank you very much.

I tried the bludtype.txt method, and nothing worked for me. I tried putting it everywhere, loading it as is, in pk3, in a separate folder, putting it inside nashgore folder, specifying full path to it - nothing. And I made sure that the line endings are CR LF. What gives? I assume fancy gibs option enables the old behavior, so with it disabled it should switch to a new system.

**Comment by Someone65** [comment]
> Excellent, thank you very much.
> 
> I tried the bludtype.txt method, and nothing worked for me. I tried putting it everywhere, loading it as is, in pk3, in a separate folder, putting it inside nashgore folder, specifying full path to it - nothing. And I made sure that the line endings are CR LF. What gives? I assume fancy gibs option enables the old behavior, so with it disabled it should switch to a new system.

It works for me with fancy gore on. Remember to load blutype.txt AFTER Nashgore (and Nashgore after DRLA Monsters) and it should work. When I had the issue of it not working, it really was only because of line endings. It's also possible what you used to save the file reconverted the line endings back?

EDIT: I checked my load order and I even put both it and Nashgore after all the DRPG related stuff but I'm not sure if that makes a difference.

**Comment by sanscriptum** [comment]
Yeah, I'm not sure. The line endings seem all correct, and it's loaded after NashGore as it should. Is there a way to see if it's loaded by the game in the console or something?
![image](https://github.com/Sumwunn/DoomRPG/assets/3057589/55192f96-d99e-4877-bc88-a81b3f4fdd6c)
![image](https://github.com/Sumwunn/DoomRPG/assets/3057589/88ccadab-6cc5-4f5a-af87-ff381cb9a3af)
![image](https://github.com/Sumwunn/DoomRPG/assets/3057589/12dcdce6-1fa5-49af-8563-70a7121569e0)
I noticed that the gore works for marines, they're definitely using the newer system (even with fancy gore off), but not monsters. With fancy gore off nothing happens for the latter, but when enabled it seems to use the old system again given the lag spike.

Edit: Oh nvm, it's definitely loading: 
![image](https://github.com/Sumwunn/DoomRPG/assets/3057589/8147eb3b-a8dd-4300-a7c1-6d0e17814a93)

**Comment by Someone65** [comment]
Wait, you're loading a folder called DoomRPG-Nashgore (which is weird because I thought there was no such thing as a DRPG patch for Nashgore) then you're loading bludtype that's already sitting INSIDE the Nashgore folder? That's really weird. You're just meant to load bludtype's lump after Nashgore, which has its own bludtype.txt that contains literally nothing that just gets replaced by the new bludtype. IDK if loading it twice screws with it or something or if you're even loading the right one since again, the one that's in Nashgore is blank.

My load order looks like the following:
`"./vkdoom.exe" -config "../../cvar inis/DoomRPG.ini" -iwad "../../IWADs/Doom2.wad" -file "../../Map wads/Megawads/WadSmoosh/doom_complete.pk3" "../../Universal mods/Cosmetic/Brightmaps Plus/bmplus_vanilla.pk3" "../../Universal mods/Cosmetic/Brightmaps Plus/bmplus_textures.pk3" "../GZDoom Stable/lights.pk3" "../../Universal mods/Sounds/Doom_Sound_Bulb.wad" "../../Universal mods/Sounds/Doom Sound_Bulb_Extra_SFX.pk3" "../../Universal mods/HUD Stuff/DmgDirOv.pk3" "../../Universal mods/HUD Stuff/damnums.pk3" "../../Universal mods/Utilities/autoautosave.pk3" "../../Universal mods/Utilities/aas-DECBot Soundpack" "../../Map wads/DOOMTEST.wad" "../../Universal mods/Cosmetic/immerse_v103.pk3" "../../Universal mods/Cosmetic/Billboarder.pk3" "../../Universal mods/Cosmetic/Dark Doom/flashlight_plus_plus_v8_5.pk3" "../../Universal mods/Cosmetic/UniversalWeaponSway.pk3" "../../Universal mods/HUD Stuff/precise-crosshair.pk3" "../../Universal mods/Utilities/gearbox.pk3" "../../Universal mods/Utilities/mod-menu.pk3" "../../Universal mods/Utilities/graveyard.pk3" "../../Universal mods/HUD Stuff/levelinfo.pk3" "../../Mod Folders/Doom RL Arsenal/DoomRL_Monsters_Beta_7.3.pk3" "../../Mod Folders/Doom RL Arsenal/Addons/DoomRL_Monsters_Brightmaps.pk3" "../../Mod Folders/Doom RL Arsenal/DoomRL_Arsenal_1.1.5.pk3" "../../Mod Folders/Doom RL Arsenal/Addons/DoomRL_Arsenal_1.1.5_Brightmaps.pk3" "../../Mod Folders/Doom RL Arsenal/Addons/doomrla_kinsie_sounds.pk3" "../../Mod Folders/Doom RL Arsenal/Addons/trar_drla_sounds.pk3" "../../Universal mods/Mutators/CorruptionCards-v5.5.pk3" "../../Mod Folders/Doom RL Arsenal/Addons/asmflow.pk3" "../../Mod Folders/Doom RL Arsenal/Addons/DRLAX_1.1c.pk3" "../../Universal mods/Mutators/LegenDoomLite_4.1.pk3" "../../Mod Folders/DoomRPG-rebalance-sync/DoomRPG" "../../Mod Folders/DoomRPG-rebalance-sync/DoomRPG-Brightmaps" "../../Mod Folders/DoomRPG-rebalance-sync/DoomRPG-RLArsenal" "../../Mod Folders/DoomRPG-rebalance-sync/DoomRPG-RLArsenal-Extended" "../../Mod Folders/DoomRPG-rebalance-sync/DoomRPG-RLMonsters" "../../Mod Folders/DoomRPG-rebalance-sync/DoomRPG-WadSmoosh" "../../Mod Folders/DoomRPG-rebalance-sync/DoomRPG-CorruptionCards" "../../Mod Folders/DoomRPG-rebalance-sync/DoomRPG-LegenDoomLite" "../../Universal mods/Gore/nashgore.pk3" "../../Universal mods/Gore/bludtype.txt" `

![image](https://github.com/Sumwunn/DoomRPG/assets/5289161/4e92d00f-419c-4f4e-817d-19462fc29cff)


EDIT: WTF why is my DRLA Monsters placed before Arsenal...? That must be what fucked up my save or something.

**Comment by sanscriptum** [comment]
Ah yes, I tried to be smart with it because DoomRPG.exe loader didn't let me load NashGore last, but even running it through a custom bat file it still doesn't work.

`"G:\gayms\doom\DoomRPG\DoomRPG-ports\GZDooM 4.12.2\gzdoom.exe" -iwad ..\..\DoomRPG-wads\doom2.wad -file ..\..\DoomRPG-mods\doom_complete.pk3 ..\..\DoomRPG-mods\mapsofchaos-ok.wad ..\..\DoomRPG-mods\Lexicon-beta-build-137.pk3 ..\..\DoomRPG-mods\Lexicon-miscdata-beta-build-137.pk3 ..\..\DoomRPG-mods\DoomRL_Arsenal_1.1.5.pk3 ..\..\DoomRPG-mods\DoomRL_Arsenal_1.1.5_Brightmaps.pk3 ..\..\DoomRPG-mods\DoomRL_Monsters_Beta_7.3.pk3 ..\..\DoomRPG-mods\DoomRL_Monsters_Brightmaps.pk3 ..\..\DoomRPG-mods\DRLAX_1.1c.pk3 "..\..\DoomRPG-mods\DoomRL Option - Kinsie Fluff.pk3" "..\..\DoomRPG-mods\DoomRL Option - Kinsie Metaprops.pk3" "..\..\DoomRPG-mods\DoomRL Option - Kinsie Sounds.pk3" "..\..\DoomRPG-mods\DoomRL Option - Sounds 2016.pk3" "..\..\DoomRPG-mods\Others - Flashlights.pk3" "..\..\DoomRPG-mods\Others - Precise Crosshair 1.4.1.pk3" "..\..\DoomRPG-mods\Others - Target Spy 2.01.pk3" "..\..\DoomRPG-mods\Others - Gearbox 0.7.0.pk3" ..\..\DoomRPG-mods\midi_floppydisk.pk7 ..\..\DoomRPG-mods\LegenDoomLite_4.1.pk3 ..\..\DoomRPG-mods\wartrophies-v1.11.0.pk3 ..\..\DoomRPG-mods\CorruptionCards-v5.1c.pk3 ..\..\DoomRPG-mods\lk_ucminimap.pk3 ..\..\DoomRPG-mods\graveyard-v1.1.1.pk3 ..\..\DoomRPG-mods\door_only.pk3 ..\..\DoomRPG-mods\Enable_Item_Rotations.pk3 "..\..\DoomRPG-mods\1 Universal Ambience.pk3" ..\..\DoomRPG-mods\Addon-NB001-Crosshairs.wad ..\..\DoomRPG-mods\autoautosave-v1.6.2.pk3 "..\..\DoomRPG-mods\Damage Direction Indicator.pk3" ..\..\DoomRPG-mods\UniversalWeaponSway.pk3 ..\..\DoomRPG-mods\AmmoDropper.pk3 ..\..\DoomRPG-mods\FlexiHUD300.pk3 ..\..\DoomRPG-mods\mk-crits[20220315].pk3 ..\..\DoomRPG-core\DoomRPG ..\..\DoomRPG-core\DoomRPG-Brightmaps ..\..\DoomRPG-core\DoomRPG-Lexicon ..\..\DoomRPG-core\DoomRPG-RLArsenal ..\..\DoomRPG-core\DoomRPG-RLMonsters ..\..\DoomRPG-core\DoomRPG-RLArsenal-Extended ..\..\DoomRPG-core\DoomRPG-CorruptionCards ..\..\DoomRPG-core\DoomRPG-WadSmoosh ..\..\DoomRPG-core\DoomRPG-LegenDoomLite "..\..\DoomRPG-core\DoomRL Option - Sounds Override" ..\..\DoomRPG-mods\nashgore.pk3 ..\..\DoomRPG-mods\bludtype.txt`

**Comment by Someone65** [comment]
[bludtype.txt](https://github.com/Sumwunn/DoomRPG/files/15364292/bludtype.txt)

Hm... maybe try this? I have absolutely no clue at this point if this doesn't work.

**Comment by sanscriptum** [comment]
Ok, so I tried to fiddle with mods to see which one causes this conflict, and you wouldn't believe it, but turns out it was DoomRPG-RLMonsters! (I could tell because with it disabled, the gibs were the ones that stick to the ceilings and stuff). It shouldn't even touch blood stuff as far as I'm aware, how does that happen? There seems to be a lot of extra stuff in master branch folder though.

Btw found a funny quirk with summoning an Archvile on the arena - if he attempts to revive any monster from the current wave, the wave will end prematurely and you can sort of speedrun the keys that way.

**Comment by Someone65** [comment]
But my load order (and your load order from your custom batch file) has DRPG RL Monsters and yet it works on my end. Maybe it forces it last if it's through the DRPG SE Launcher? Honestly I just recommend using [Doomrunner](https://github.com/Youda008/DoomRunner) if you already know how to work with load orders at this point. Also, you should open a separate issue for the Archvile bug as a report. I haven't really messed with summons much yet but that sounds hilarious.

**Comment by sanscriptum** [comment]
Sadly, doesn't work. With both .bat and Doomrunner, it's loaded last and it's confirmed in the console as well. I'm not sure what's going on anymore.

**Comment by Sumwunn** [comment]
Apologies for the rough experience you had transitioning to this. I didn't except many to find this build since I contained it to GitHub only. A lot of DRPG's code has changed with this build, including how WAD progress is saved; now, it's separated from Character saves so there shouldn't be anymore issues there.

I updated the README appropriately.

**Comment by sanscriptum** [comment]
Ok, I singled out a file that was causing the issue - it's MAPINFO.txt from DoomRPG-RLMonsters. It seems to be replacing monster types compared to vanilla DoomRL_Monsters, and that somehow breaks NashGore, specifically if skill is set to anything but 0. With skill 0, gibs appear as they should, wtf?

Funnily enough, bludtype isn't even needed for it to work, as long as MAPINFO is removed. Any ideas why it's being so stubborn with it?

**Comment by Sumwunn** [comment]
Do a fresh install.

**Comment by Sumwunn** [comment]
Also, I have no interest in NashGore NEXT and cannot do anything from my side since the issue lies within the compatible mods.

You're more likely to get a potential answer on ZDoom.

[DoomRL Arsenal Thread](https://forum.zdoom.org/viewtopic.php?t=37044)
[NashGore Next Thread](https://forum.zdoom.org/viewtopic.php?t=78997)

**Comment by sanscriptum** [comment]
Fresh install it is then. Results - no gibs on either master branch or rebalance-sync, unless started with skill 0 or MAPINFO.txt is removed. It's truly bizarre, oh well.

Edit: Interesting development - previous version, Nashgore Vengeance, works without a hitch unlike Next. Why? No idea, gonna research.
