### ISSUE TITLE
Misc issues

### ISSUE THREAD

**Issue by sanscriptum** [Sumwunn/DoomRPG#97]
* How does Cerberus armor set work? I have boots and the armor, and the set bonus didn't apply for some reason. Do they work differently? EDIT: Oh turns out it needs Tristar Launcher as well for the full set, lame.
* Does Trespasser's special item scanner even work? I tried to roll a crate in front of me and I haven't gotten the item I've scanned (Gothic Boots) even once, despite it being a very rare chest. I then tried to scan some random mundane item like Chaingun, and it also didn't appear at all, in both cases I've made at least 50 tries.
* Not sure if intentional, but Heavy Pulse Blaster seems to be able to kill friendly summons by shooting at them.
* Scattershot from Trespasser can occasionally hit friendlies and insta oneshot them if it pierced through them, or chained near them.
* The LIL-ZZ8 shield accessory doesn't correctly count fully completed maps for the purpose of scaling, only giving one stack. Or does it not apply retroactively? (I had like 20 fully cleared maps prior).
* Weaken doesn't show the warning about the target being too powerful when it doesn't work on super bosses (like Soul Steal).
* Maybe put cooldown timers for Time Stop and increased skill cost in the skill menu? So at least you know how long you need to wait.
* Jackal pistol doesn't seem to activate triggers when shooting the green eyes on Sigil maps (mine has Firestorm modpack, maybe that's the issue?).
* Extra life doesn't activate when your character gets gibbed, is that intentional?
* Is it possible to make items you own visible on item assembling screens? It's inconvenient to check the inventory manually every time.
* There seems to be a Superboss flag (my own name) of some sort for monsters who drop Demon Artifact and are immune to cheese strategies by having immunities to many skills and powerful weaponry, so they have to be brought down by conventional weapons and overwhelming raw damage. Especially the Abominant who is very annoying to fight given how tanky he is. Can they be given some sort of tag for the HP bar to give the heads up for their special status? Unless the chevrons next to the name already indicated that, then nvm.
* Heal skill that gives twice the health will decay to base health regardless if you've already had extra health from Megasphere for example (e.g. had 900 health, it'll trickle down to 400). Is that intended?
* COUN-TR20 shield accessory doesn't seem to trigger the explosion when you enter a new level with the Corruption Cards mod, at least that's my assumption, maybe it doesn't work at all. Same thing with MUN3-MAG's explosion at charge or depletion actually, the soundbyte plays, but no boom occurs.
* This is a minor nitpick, but it seems that the shield accessory effects have been rebalanced and moved around recently, which made all of the Touhou-themed accessories have wrong effects, like FLAN-495 used to explode enemies, TOJ1-K0 emit lightning, etc. Some other parts have also lost their theme, like RNJSUS-2 that used to scale off luck. Maybe restore them somehow? (Move the name and the icon?)
* In the Hub, sometimes targets on the firing range can "die" from certain weapons and don't display damage numbers anymore.

**Comment by Someone65** [comment]
The trespasser's special item scanner should THEORETICALLY work as it does have code specifically for DRPG... but idk shit about coding so when I looked into it, I couldn't actually tell whether or not it was properly implemented and working. I will say that there was an instance here and there where I rolled the armor I had scanned an unusual number of times (to the point of getting annoying) from crates but I have no earthly clue whether or not it was because of the tracking or just a coincidence.

**Comment by sanscriptum** [comment]
I checked the code as well, and it looked a bit bizarre because it was in the ``WorldThingDied`` section? Which would imply that it fires up only after the crate has been looted and "died", maybe? Then it's followed up by a check if Trespasser's item is in the inventory, before trying this check: ``if(inv.levels.Find(Level.LevelName) == inv.levels.Size())``, which again I find weird. Surely it has nothing to do with the map or level pack itself, it probably just looks if there's a free slot in the inventory? Then in 1/4 chance it should spawn the scanned item, but not inside the crate, but more like a world spawn? It's really weird. I tried to always return true for both of those checks I mentioned, but nothing has changed.

**Comment by WNC12k** [comment]
> Does Trespasser's special item scanner even work? I tried to roll a crate in front of me and I haven't gotten the item I've scanned (Gothic Boots) even once, despite it being a very rare chest. I then tried to scan some random mundane item like Chaingun, and it also didn't appear at all, in both cases I've made at least 50 tries.

It's working. As I remember now - I thought for a long time how to fit it into the balance - so that it could not be used to dup items. I had to make a small increase in the chance of appearance of scanned item - but it is still more than the usual. In general crates in the rebalance - severely cut to be a challenge - so I had to do it this way.

In rebalance now works accumulative system of item chance - for example there is a pool of items - boots of one (certain) level - when one item from the pool falls out - the chances of its appearance are reduced, so that other items from the pool can fall out. Each pool also has its own drop chance - and it works the same way - to bring variety in finding items (not just random).

And Trespasser's special item scanner had to be incorporated into this system to make it all work together and not upset the balance.

After all, I didn't know at the time that the developer of DRLA Extended was planning to do such a thing :D

**Comment by WNC12k** [comment]
Anyway, there were a few things in DRLA Extended that had to be changed so they could fit into the rebalance. For example, the Nomad is a very heavily redesigned character. In order for him to make any sense at all to play in a DoomRPG.

**Comment by sanscriptum** [comment]
Hmm, I've never gotten a single scanned item as a Trespasser, so I guess it works as intended then. I have a higher chance at getting Legendary at level 1 by stealing them from the Hub at this point 😂

**Comment by Sumwunn** [comment]
Post to Rebalance GitHub page.
